-- identifica factura con su requisicion

SELECT DISTINCT
    ILA.INVOICE_ID,
    PRHA.REQUISITION_NUMBER
FROM
    AP_INVOICE_LINES_ALL ILA
JOIN PO_LINE_LOCATIONS_ALL PLL ON ILA.PO_LINE_LOCATION_ID = PLL.LINE_LOCATION_ID
JOIN PO_DISTRIBUTIONS_ALL PDA ON PLL.LINE_LOCATION_ID = PDA.LINE_LOCATION_ID
JOIN POR_REQ_DISTRIBUTIONS_ALL PRDA ON PDA.REQ_DISTRIBUTION_ID = PRDA.DISTRIBUTION_ID
JOIN POR_REQUISITION_LINES_ALL PRLA ON PRDA.REQUISITION_LINE_ID = PRLA.REQUISITION_LINE_ID
JOIN POR_REQUISITION_HEADERS_ALL PRHA ON PRLA.REQUISITION_HEADER_ID = PRHA.REQUISITION_HEADER_ID
WHERE
    ILA.LINE_TYPE_LOOKUP_CODE = 'ITEM'