SELECT
    AIL.INVOICE_ID,
    NVL(AIL.TAX_RATE, 0) AS TAX_RATE,
    AIL.AMOUNT AS TAX_AMT,
    AIL.LINE_TYPE_LOOKUP_CODE AS TIPO_LINEA,
    AIL.TAX_RATE_CODE as CODIGO_IMPUESTO
FROM
    AP_INVOICE_LINES_ALL AIL
WHERE
    AIL.LINE_TYPE_LOOKUP_CODE IN ('TAX', 'AWT')
    AND AIL.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
