SELECT
    AIP.INVOICE_ID,
    AC.CHECK_NUMBER AS NUM_PAGO,
    TO_CHAR(AC.CHECK_DATE, 'YYYY-MM-DD') AS FECHA_PAGO,
    TO_CHAR(AIP.ACCOUNTING_DATE, 'YYYY-MM-DD') AS FECHA_APLICACION,
    -- Intentamos obtener el nombre de la cuenta bancaria desde la tabla de cheques directamente si existe
    AC.BANK_ACCOUNT_NAME AS BANCO_CUENTA,
    AIP.AMOUNT AS IMPORTE_PAGO,
    AIP.DISCOUNT_TAKEN AS ADELANTO_APLICADO,
    AC.CURRENCY_CODE AS MONEDA_PAGO,
    AC.EXCHANGE_RATE AS TC_PAGO
FROM
    AP_INVOICE_PAYMENTS_ALL AIP
    INNER JOIN AP_CHECKS_ALL AC ON AIP.CHECK_ID = AC.CHECK_ID
WHERE
    AC.STATUS_LOOKUP_CODE = 'CLEARED'
    AND AIP.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')