SELECT DISTINCT
    AIL.INVOICE_ID,
    gc.SEGMENT5 AS CUENTA_NUM
FROM
    AP_INVOICE_LINES_ALL AIL,
    PO_DISTRIBUTIONS_ALL PDA,
    GL_CODE_COMBINATIONS gc
WHERE
    AIL.PO_LINE_LOCATION_ID = PDA.LINE_LOCATION_ID
    AND PDA.CODE_COMBINATION_ID = gc.CODE_COMBINATION_ID
    AND gc.SEGMENT5 LIKE '5%' -- Solo gastos para auditoría
    AND AIL.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')