SELECT
    IA.INVOICE_ID,
    HOU.NAME as EMPRESA,
    SUP.SEGMENT1 as NUM_PROV,
    HP.PARTY_NAME as PROVEEDOR,
    POZPII.INCOME_TAX_ID as RFC,
    IA.INVOICE_NUM as FACTURA,
    -- Subconsulta para obtener el Número de Recepción (Receipt Number)
    (SELECT DISTINCT RSH.RECEIPT_NUM
     FROM AP_INVOICE_DISTRIBUTIONS_ALL AID,
          RCV_TRANSACTIONS RT,
          RCV_SHIPMENT_HEADERS RSH
     WHERE AID.INVOICE_ID = IA.INVOICE_ID
     AND AID.RCV_TRANSACTION_ID = RT.TRANSACTION_ID
     AND RT.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
     AND ROWNUM = 1) as ERS,
    IA.SOURCE as ORIGEN,
    IA.PAYMENT_STATUS_FLAG as ESTATUS,
    IA.GLOBAL_ATTRIBUTE1 as UUID,
    TO_CHAR(IA.INVOICE_DATE, 'YYYY-MM-DD') as FECHA,
    IA.INVOICE_CURRENCY_CODE as MONEDA,
    IA.DESCRIPTION,
    IA.INVOICE_AMOUNT as IMPORTE,
    (SELECT GCC.SEGMENT1||'-'||GCC.SEGMENT2||'-'||GCC.SEGMENT3||'-'||GCC.SEGMENT4||'-'||GCC.SEGMENT5||'-'||GCC.SEGMENT6
     FROM GL_CODE_COMBINATIONS GCC
     WHERE GCC.CODE_COMBINATION_ID = IA.ACCTS_PAY_CODE_COMBINATION_ID) as CUENTA_BALANCE,
    (SELECT GCC.SEGMENT1||'-'||GCC.SEGMENT2||'-'||GCC.SEGMENT3||'-'||GCC.SEGMENT4||'-'||GCC.SEGMENT5||'-'||GCC.SEGMENT6
     FROM AP_INVOICE_DISTRIBUTIONS_ALL AID, GL_CODE_COMBINATIONS GCC
     WHERE AID.INVOICE_ID = IA.INVOICE_ID
     AND AID.DIST_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
     AND AID.LINE_TYPE_LOOKUP_CODE <> 'TAX'
     AND ROWNUM = 1) as CUENTA_GASTO
FROM
    AP_INVOICES_ALL IA
    INNER JOIN POZ_SUPPLIERS SUP ON IA.VENDOR_ID = SUP.VENDOR_ID
    INNER JOIN HZ_PARTIES HP ON SUP.PARTY_ID = HP.PARTY_ID
    INNER JOIN HR_OPERATING_UNITS HOU ON IA.ORG_ID = HOU.ORGANIZATION_ID
    LEFT JOIN POZ_SUPPLIERS_PII POZPII ON SUP.VENDOR_ID = POZPII.VENDOR_ID
WHERE
    IA.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')\