SELECT
    AIL.INVOICE_ID,
    NVL(AIL.TAX_RATE, 0) AS TAX_RATE,
    AIL.AMOUNT AS TAX_AMT,
    AIL.LINE_TYPE_LOOKUP_CODE AS TIPO_LINEA,
    -- Usamos el código de tasa que es el campo más común en líneas
    AIL.TAX_RATE_CODE
FROM
    AP_INVOICE_LINES_ALL AIL
WHERE
    AIL.LINE_TYPE_LOOKUP_CODE = 'TAX'
    AND AIL.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')