SELECT
    AIP.INVOICE_ID,
    AC.CHECK_NUMBER as NUM_PAGO,
    TO_CHAR(AC.CHECK_DATE, 'YYYY-MM-DD') as FECHA_PAGO,
    TO_CHAR(AIP.ACCOUNTING_DATE, 'YYYY-MM-DD') as FECHA_APLICACION,
    AC.BANK_ACCOUNT_NAME as BANCO_CUENTA,
    AIP.AMOUNT as IMPORTE_PAGO,
    AIP.DISCOUNT_TAKEN as ADELANTO_APLICADO -- Monto de anticipos/descuentos
FROM
    AP_INVOICE_PAYMENTS_ALL AIP
    JOIN AP_CHECKS_ALL AC ON AIP.CHECK_ID = AC.CHECK_ID