SELECT
    TO_CHAR(CONVERSION_DATE, 'YYYY-MM-DD') as FECHA_TASA,
    FROM_CURRENCY,
    TO_CURRENCY,
    CONVERSION_RATE
FROM
    GL_DAILY_RATES
WHERE
    FROM_CURRENCY = 'USD'
    AND TO_CURRENCY = 'MXN'
    AND CONVERSION_TYPE = 'Corporate'
    AND CONVERSION_DATE >= TO_DATE('2024-01-01', 'YYYY-MM-DD')
ORDER BY
    CONVERSION_DATE DESC