SELECT
    b.INVOICE_ID,
    b.INVOICE_NUM AS FACTURA,
    b.VOUCHER_NUM,
    b.INVOICE_AMOUNT,
    b.TOTAL_TAX_AMOUNT,
    b.INVOICE_DATE AS FECHA,
    b.TERMS_DATE,
    b.INVOICE_CURRENCY_CODE AS MONEDA,
    b.EXCHANGE_RATE AS TIPO_CAMBIO_FACTURA,
    b.GLOBAL_ATTRIBUTE1,
    b.GLOBAL_ATTRIBUTE2 AS UUID,
    b.SOURCE AS ORIGEN,
    b.APPROVAL_STATUS AS ESTATUS,
    b.INVOICE_TYPE_LOOKUP_CODE AS TIPO,
    b.VENDOR_ID,
    b.ORG_ID,
    b.TERMS_ID,
    c.SEGMENT1 AS NUM_PROV,
    c.VENDOR_NAME AS PROVEEDOR,
    c.ORGANIZATION_TYPE_LOOKUP_CODE,
    d.NAME AS EMPRESA,
    e.INCOME_TAX_ID,
    f.DUE_DAYS,
    (
        SELECT MAX(POH.SEGMENT1)
        FROM AP_INVOICE_DISTRIBUTIONS_ALL IDA2
        JOIN PO_DISTRIBUTIONS_ALL PDA2 ON IDA2.PO_DISTRIBUTION_ID = PDA2.PO_DISTRIBUTION_ID
        JOIN PO_HEADERS_ALL POH ON PDA2.PO_HEADER_ID = POH.PO_HEADER_ID
        WHERE IDA2.INVOICE_ID = b.INVOICE_ID
    ) AS ORDEN_COMPRA,
    NULL AS RFC
FROM AP_INVOICES_ALL b
JOIN POZ_SUPPLIERS_V c ON b.VENDOR_ID = c.VENDOR_ID
JOIN HR_ALL_ORGANIZATION_UNITS_F_VL d ON d.ORGANIZATION_ID = b.ORG_ID
JOIN POZ_SUPPLIERS_PII e ON e.VENDOR_ID = c.VENDOR_ID
JOIN AP_TERMS_LINES f ON f.TERM_ID = b.TERMS_ID
WHERE b.INVOICE_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
ORDER BY b.INVOICE_DATE DESC