SELECT
    aid.INVOICE_ID,
    aid.DISTRIBUTION_LINE_NUMBER,
    aid.DESCRIPTION,
    aid.AMOUNT AS IMPORTE_DISTRIBUCION_USD,
    aid.DIST_CODE_COMBINATION_ID,
    gcc.SEGMENT1 || '.' || gcc.SEGMENT2 || '.' || gcc.SEGMENT3 || '.' || gcc.SEGMENT4 || '.' || gcc.SEGMENT5 AS CUENTA_CONTABLE_GASTO,
    gcc.SEGMENT1 AS CC_EMPRESA,
    gcc.SEGMENT2 AS CC_DEPARTAMENTO,
    gcc.SEGMENT3 AS CC_CUENTA
FROM AP_INVOICE_DISTRIBUTIONS_ALL aid
LEFT JOIN GL_CODE_COMBINATIONS gcc 
    ON aid.DIST_CODE_COMBINATION_ID = gcc.CODE_COMBINATION_ID
WHERE aid.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
ORDER BY aid.INVOICE_ID, aid.DISTRIBUTION_LINE_NUMBER