SELECT
    INVOICE_ID,
    PAYMENT_NUM,
    DUE_DATE AS FECHA_VENCIMIENTO,
    GROSS_AMOUNT AS IMPORTE_BRUTO_USD,
    AMOUNT_REMAINING AS SALDO_USD,
    PAYMENT_PRIORITY
FROM AP_PAYMENT_SCHEDULES_ALL
WHERE CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
ORDER BY INVOICE_ID, PAYMENT_NUM