SELECT
    aip.INVOICE_ID,
    aip.CHECK_ID,
    ac.CHECK_NUMBER AS NUM_PAGO,
    ac.BANK_ACCOUNT_NAME AS BANCO_CUENTA,
    aip.ACCOUNTING_DATE AS FECHA_APLICACION,
    aip.AMOUNT AS IMPORTE_PAGO_USD,
    aip.INVOICE_BASE_AMOUNT AS IMPORTE_PAGO_MXN,
    aip.EXCHANGE_RATE AS TIPO_CAMBIO_PAGO,
    ac.CURRENCY_CODE AS MONEDA_PAGO
FROM AP_INVOICE_PAYMENTS_ALL aip
JOIN AP_CHECKS_ALL ac ON aip.CHECK_ID = ac.CHECK_ID
WHERE aip.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
ORDER BY aip.INVOICE_ID, aip.ACCOUNTING_DATE DESC