SELECT
    aph.INVOICE_ID,
    aph.PREPAY_INVOICE_ID,
    inv.INVOICE_AMOUNT AS ADELANTO_USD,
    aph.ACCOUNTING_DATE AS FECHA_APLICACION,
    inv.INVOICE_CURRENCY_CODE AS MONEDA,
    inv.EXCHANGE_RATE AS TIPO_CAMBIO,
    'PREPAYMENT' AS TIPO_ORIGEN,
    NULL AS ERS,
    NULL AS ORDEN_COMPRA
FROM AP_PREPAY_HISTORY_ALL aph
LEFT JOIN AP_INVOICES_ALL inv ON aph.PREPAY_INVOICE_ID = inv.INVOICE_ID
WHERE aph.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')

UNION ALL

SELECT
    NULL AS INVOICE_ID,
    NULL AS PREPAY_INVOICE_ID,
    NULL AS ADELANTO_USD,
    rcv.TRANSACTION_DATE AS FECHA_APLICACION,
    NULL AS MONEDA,
    NULL AS TIPO_CAMBIO,
    'ERS' AS TIPO_ORIGEN,
    rcv.SOURCE_TRANSACTION_NUM AS ERS,
    poh.SEGMENT1 AS ORDEN_COMPRA
FROM RCV_TRANSACTIONS rcv
LEFT JOIN PO_HEADERS_ALL poh ON rcv.PO_HEADER_ID = poh.PO_HEADER_ID
WHERE rcv.TRANSACTION_TYPE = 'RECEIVE'
  AND rcv.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')

ORDER BY TIPO_ORIGEN, FECHA_APLICACION DESC