SELECT
    TRX_ID AS INVOICE_ID,
    TRX_LINE_NUMBER,
    TAX_TYPE_CODE,
    TAX_AMT AS IMPUESTO_USD,
    TAX_AMT_FUNCL_CURR AS IMPUESTO_MXN,
    TAX_CURRENCY_CODE,
    CURRENCY_CONVERSION_RATE
FROM ZX_LINES
WHERE CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
  AND TAX_AMT <> 0
ORDER BY TRX_ID, TRX_LINE_NUMBER