SELECT
    awt.INVOICE_ID,
    inv.INVOICE_NUM AS FACTURA,
    awt.DISTRIBUTION_LINE_NUMBER,
    awt.AMOUNT AS RETENCION_USD,
    awt.BASE_AMOUNT AS RETENCION_MXN,
    awt.WITHHOLDING_TAX_CODE_ID,
    tax.TAX AS NOMBRE_IMPUESTO,
    tax.TAX_REGIME_CODE,
    item_lines.AMOUNT_BASE AS MONTO_BASE,
    ROUND((ABS(awt.AMOUNT) / NULLIF(ABS(item_lines.AMOUNT_BASE), 0)) * 100, 2) AS PORCENTAJE_RETENCION,
    CASE
        WHEN ROUND((ABS(awt.AMOUNT) / NULLIF(ABS(item_lines.AMOUNT_BASE), 0)) * 100, 2) = 4 THEN 'RET_ISR_4'
        WHEN ROUND((ABS(awt.AMOUNT) / NULLIF(ABS(item_lines.AMOUNT_BASE), 0)) * 100, 2) = 1.25 THEN 'RET_ISR_125'
        WHEN ROUND((ABS(awt.AMOUNT) / NULLIF(ABS(item_lines.AMOUNT_BASE), 0)) * 100, 2) = 10.66 THEN 'RET_IVA'
        WHEN ROUND((ABS(awt.AMOUNT) / NULLIF(ABS(item_lines.AMOUNT_BASE), 0)) * 100, 2) = 10 THEN 'RET_ISR_10'
        WHEN ROUND((ABS(awt.AMOUNT) / NULLIF(ABS(item_lines.AMOUNT_BASE), 0)) * 100, 2) = 6 THEN 'RET_IVA_6'
        ELSE 'RET_OTRO'
    END AS CLASIFICACION_RETENCION,
    awt.ACCOUNTING_DATE AS FECHA_APLICACION
FROM AP_INVOICE_DISTRIBUTIONS_ALL awt
JOIN AP_INVOICES_ALL inv ON awt.INVOICE_ID = inv.INVOICE_ID
LEFT JOIN ZX_TAXES_B tax ON awt.WITHHOLDING_TAX_CODE_ID = tax.TAX_ID
JOIN (
    SELECT INVOICE_ID, SUM(AMOUNT) AS AMOUNT_BASE
    FROM AP_INVOICE_DISTRIBUTIONS_ALL
    WHERE LINE_TYPE_LOOKUP_CODE = 'ITEM'
    GROUP BY INVOICE_ID
) item_lines ON awt.INVOICE_ID = item_lines.INVOICE_ID
WHERE awt.LINE_TYPE_LOOKUP_CODE = 'AWT'
AND awt.CREATION_DATE >= TO_DATE('2025-01-01', 'YYYY-MM-DD')
ORDER BY awt.INVOICE_ID, awt.DISTRIBUTION_LINE_NUMBER